import type { NoiseDefinition, NoiseKind, NoiseParams, Preset } from "./types";
const base: NoiseParams = {
  scale: 2,
  amount: 0.5,
  detail: 4,
  speed: 1,
  colorMode: "mono",
  color: "#c6b8fa",
};
const rows: [
  NoiseKind,
  string,
  string,
  string,
  string,
  Partial<NoiseParams>,
  string,
  string,
  string,
  boolean?,
][] = [
  [
    "uniform",
    "均一ノイズ",
    "Uniform",
    "粒状",
    "明るさが均等に散らばる、素直なランダムの粒。",
    { amount: 0.8 },
    "粒の大きさ",
    "コントラスト",
    "粒の密度",
  ],
  [
    "gaussian",
    "ガウスノイズ",
    "Gaussian",
    "粒状",
    "中間の明るさが多い、自然でやわらかな粒。",
    { scale: 1.5, amount: 0.18, detail: 8 },
    "粒の大きさ",
    "シグマ（粒の強さ）",
    "粒の密度",
  ],
  [
    "salt-pepper",
    "塩胡椒ノイズ",
    "Salt & pepper",
    "粒状",
    "白と黒の点を散らして、ざらっとした表情に。",
    { amount: 0.12 },
    "点の大きさ",
    "点の密度",
    "白と黒の比率",
  ],
  [
    "value",
    "Value ノイズ",
    "Value",
    "パターン",
    "ランダムな明暗をなめらかにつないだ模様。",
    { scale: 120 },
    "模様の大きさ",
    "コントラスト",
    "輪郭の強さ",
  ],
  [
    "perlin",
    "Perlin ノイズ",
    "Perlin",
    "パターン",
    "自然にうねる濃淡。地形やゆらぎの素材に。",
    { scale: 140 },
    "模様の大きさ",
    "コントラスト",
    "輪郭の強さ",
  ],
  [
    "simplex",
    "Simplex ノイズ",
    "Simplex",
    "パターン",
    "方向に偏りにくい、なめらかな濃淡の模様。",
    { scale: 150 },
    "模様の大きさ",
    "コントラスト",
    "輪郭の強さ",
  ],
  [
    "worley",
    "Worley ノイズ",
    "Worley",
    "パターン",
    "細胞や石のような、隣り合う領域の模様。",
    { scale: 100 },
    "セルの大きさ",
    "コントラスト",
    "境界の強さ",
  ],
  [
    "fbm",
    "フラクタル雲",
    "Fractal clouds",
    "パターン",
    "大小のゆらぎを重ねた、奥行きのある雲。",
    { scale: 180, amount: 0.65, detail: 5 },
    "雲の大きさ",
    "コントラスト",
    "重ねる細かさ",
  ],
  [
    "turbulence",
    "乱流",
    "Turbulence",
    "パターン",
    "折り重なる濃淡で、煙や流れの質感を作る。",
    { scale: 150, detail: 5 },
    "流れの大きさ",
    "コントラスト",
    "重ねる細かさ",
  ],
  [
    "marble",
    "マーブル",
    "Marble",
    "パターン",
    "ゆらぎのある縞模様で、大理石のような表情に。",
    { scale: 130 },
    "縞の間隔",
    "うねりの強さ",
    "うねりの細かさ",
  ],
  [
    "grain",
    "フィルムグレイン",
    "Film grain",
    "フィルム",
    "細かな粒が明暗を揺らす、フィルム風の質感。",
    { scale: 1.3, amount: 0.2 },
    "粒の大きさ",
    "粒の強さ",
    "粒の密度",
  ],
  [
    "scratches",
    "縦傷",
    "Scratches",
    "フィルム",
    "古いフィルムを思わせる、途切れた縦の傷。",
    { scale: 65, amount: 0.35 },
    "傷の間隔",
    "傷の密度",
    "傷の太さ",
  ],
  [
    "dust",
    "ほこり",
    "Dust",
    "フィルム",
    "小さなほこりをまばらに散らす。",
    { scale: 55, amount: 0.3 },
    "点の間隔",
    "ほこりの密度",
    "ほこりの大きさ",
  ],
  [
    "flicker",
    "ちらつき",
    "Flicker",
    "フィルム",
    "画面全体の明るさが、時間とともに揺れる。",
    { amount: 0.15 },
    "揺れの周期",
    "明るさの変化",
    "揺れの細かさ",
  ],
  [
    "scanlines",
    "走査線",
    "Scanlines",
    "アナログ",
    "ブラウン管のような、規則的な水平線。",
    { scale: 4, amount: 0.4 },
    "線の間隔",
    "線の濃さ",
    "線の太さ",
  ],
  [
    "sync",
    "水平同期ずれ",
    "Horizontal drift",
    "アナログ",
    "下の画像を横方向にずらして、映像の乱れに。",
    { scale: 65, amount: 0.2 },
    "ずれる帯の高さ",
    "ずれの強さ",
    "揺れの細かさ",
    true,
  ],
  [
    "rgb-shift",
    "RGB色ずれ",
    "RGB shift",
    "アナログ",
    "下の画像の赤・緑・青をずらし、色の輪郭を作る。",
    { scale: 4, amount: 0.6 },
    "色のずれ幅",
    "ずれの強さ",
    "ずれの方向",
    true,
  ],
  [
    "glitch",
    "ブロックグリッチ",
    "Block glitch",
    "アナログ",
    "下の画像をブロックごとにずらして、信号の乱れに。",
    { scale: 65, amount: 0.25 },
    "ブロックの大きさ",
    "乱れの密度",
    "ずれの強さ",
    true,
  ],
  [
    "paper",
    "紙の繊維",
    "Paper fibers",
    "テクスチャ",
    "細く重なる繊維で、紙の手触りを表現する。",
    { scale: 3, amount: 0.3, colorMode: "tint", color: "#e5dccb" },
    "繊維の大きさ",
    "繊維の強さ",
    "繊維の長さ",
  ],
  [
    "dither",
    "ディザ風ドット",
    "Dither dots",
    "テクスチャ",
    "規則的なドットと濃淡で、印刷風の表情に。",
    { scale: 5, amount: 0.55 },
    "ドットの大きさ",
    "ドットの濃さ",
    "濃淡の変化",
  ],
];
// Append kinds: the renderer dispatch order also preserves existing projects.
rows.push(
  [
    "grunge",
    "グランジスクラッチ",
    "Grunge scratches",
    "テクスチャ",
    "斜めに交差する細かな擦り傷と、使い込んだ表面の汚れ。",
    { scale: 65, amount: 0.65, detail: 6, speed: 0.1 },
    "傷の長さ",
    "傷と汚れの強さ",
    "傷の重なり",
  ],
  [
    "film-damage",
    "フィルムダメージ",
    "Film damage",
    "フィルム",
    "不揃いなほこり、糸くず、途切れた縦傷を散らす透過素材。",
    { scale: 35, amount: 0.45, detail: 5, speed: 0.3 },
    "ほこりの間隔",
    "ダメージの密度",
    "傷の量",
  ],
  [
    "signal-noise",
    "RGBシグナル",
    "RGB signal",
    "アナログ",
    "黒い隙間を挟んだ虹色の横帯と、細かく裂けた信号の光。",
    { scale: 55, amount: 0.7, detail: 6, colorMode: "rgb" },
    "信号帯の大きさ",
    "信号の密度",
    "信号の細かさ",
  ],
  [
    "glitch-flare",
    "グリッチフレア",
    "Glitch flare",
    "アナログ",
    "白くにじむ光の中心から、色の縁を持つ横筋が伸びる。",
    { scale: 85, amount: 0.65, detail: 5, colorMode: "rgb" },
    "光の広がり",
    "発光の強さ",
    "横筋の細かさ",
  ],
  [
    "color-film",
    "カラーフィルム",
    "Color film",
    "フィルム",
    "赤と青の色ムラ、微細な粒、古いフィルムの擦れを重ねる。",
    { scale: 110, amount: 0.6, detail: 5, colorMode: "rgb", speed: 0.15 },
    "色ムラの大きさ",
    "粒と色の強さ",
    "表面の荒れ",
  ],
);
rows.push(
  [
    "latent-bloom",
    "生成崩壊ブルーム",
    "Latent bloom",
    "パターン",
    "黒い隙間に、溶けた虹色と白い塊が浮かぶ生成失敗風の模様。",
    { scale: 18, amount: 0.65, detail: 5, colorMode: "rgb", speed: 0.5 },
    "塊の大きさ",
    "色のあふれ",
    "形の崩れ",
  ],
  [
    "decode-noise",
    "デコード崩れ",
    "Decode noise",
    "アナログ",
    "細かなRGBの砂嵐に、赤・緑・青の崩れた横帯が混ざる。",
    { scale: 1, amount: 0.65, detail: 5, colorMode: "rgb", speed: 1 },
    "粒の大きさ",
    "色帯の強さ",
    "色帯の数",
  ],
);
rows.push([
  "color-snow",
  "カラー砂嵐",
  "Color snow",
  "粒状",
  "デコード崩れから色帯を除いた、細かなカラーだけの砂嵐。",
  { scale: 1, amount: 0.78, detail: 4, colorMode: "rgb", speed: 1 },
  "粒の大きさ",
  "粒のコントラスト",
  "明るさ",
]);
export const definitions: NoiseDefinition[] = rows.map(
  (
    [
      id,
      name,
      english,
      category,
      description,
      params,
      scale,
      amount,
      detail,
      effect,
    ],
    i,
  ) => ({
    id,
    code: String(i + 1).padStart(2, "0"),
    name,
    english,
    category,
    description,
    defaults: { ...base, ...params },
    controls: { scale, amount, detail },
    effect,
  }),
);
export function getDefinition(kind: NoiseKind): NoiseDefinition {
  const d = definitions.find((d) => d.id === kind);
  if (!d) throw new Error("不明なノイズです");
  return d;
}
export const presets: Preset[] = [
  {
    id: "film",
    name: "古い映画",
    description: "時間をまとった、フィルムの粒と傷。",
    backgroundColor: "#34313c",
    layers: [
      { kind: "grain", blend: "soft-light", opacity: 0.8 },
      { kind: "scratches", opacity: 0.45 },
      { kind: "dust", opacity: 0.5 },
      { kind: "flicker", blend: "screen", opacity: 0.3 },
    ],
  },
  {
    id: "vhs",
    name: "VHS",
    description: "走査線と色ずれ。あの頃の映像に。",
    backgroundColor: "#292d45",
    layers: [
      { kind: "fbm", params: { colorMode: "tint", color: "#b8a4ed" } },
      { kind: "grain", blend: "soft-light", opacity: 0.5 },
      { kind: "scanlines", opacity: 0.55 },
      { kind: "sync" },
      { kind: "rgb-shift", params: { scale: 7 } },
    ],
  },
  {
    id: "print",
    name: "印刷の粒",
    description: "ざらつきと網点がつくる印刷の手触り。",
    backgroundColor: "#d8cec0",
    layers: [
      { kind: "gaussian", blend: "multiply", opacity: 0.5 },
      { kind: "dither", blend: "soft-light", opacity: 0.65 },
    ],
  },
  {
    id: "cloud",
    name: "雲",
    description: "幾重にも重なる、やわらかな濃淡。",
    backgroundColor: "#202534",
    layers: [
      {
        kind: "fbm",
        params: {
          colorMode: "tint",
          color: "#c2b5f5",
          scale: 180,
          amount: 0.75,
        },
      },
      {
        kind: "turbulence",
        blend: "soft-light",
        opacity: 0.3,
        params: { scale: 120 },
      },
      { kind: "grain", blend: "soft-light", opacity: 0.25 },
    ],
  },
  {
    id: "paper",
    name: "紙",
    description: "淡い繊維と、細かな粒の重なり。",
    backgroundColor: "#ede3d1",
    layers: [
      { kind: "paper", blend: "multiply", opacity: 0.75 },
      {
        kind: "gaussian",
        blend: "multiply",
        opacity: 0.2,
        params: { amount: 0.08 },
      },
    ],
  },
  {
    id: "color",
    name: "カラースタティック",
    description: "赤・緑・青が弾ける、鮮やかなランダム。",
    backgroundColor: "#14151b",
    layers: [
      { kind: "uniform", params: { colorMode: "rgb", scale: 2, amount: 1 } },
      { kind: "rgb-shift", params: { scale: 3 } },
    ],
  },
];

presets.push(
  {
    id: "dark-grunge",
    name: "ダークグランジ",
    description: "細い擦り傷が交差する、使い込んだ表面。",
    backgroundColor: "#151515",
    layers: [
      { kind: "grunge" },
      {
        kind: "film-damage",
        opacity: 0.35,
        params: { amount: 0.22, detail: 2 },
      },
    ],
  },
  {
    id: "damaged-film",
    name: "ダストフィルム",
    description: "黒地に浮かぶ白いほこりと縦傷。スクリーン合成にも。",
    backgroundColor: "#000000",
    layers: [
      { kind: "film-damage" },
      {
        kind: "scratches",
        opacity: 0.5,
        params: { scale: 150, amount: 0.3, detail: 1 },
      },
    ],
  },
  {
    id: "rgb-signal",
    name: "RGBシグナル",
    description: "細かい虹色の横帯が走る、壊れた映像信号。",
    backgroundColor: "#000000",
    layers: [{ kind: "signal-noise" }, { kind: "film-damage", opacity: 0.15 }],
  },
  {
    id: "chroma-blocks",
    name: "クロマブロック",
    description: "太い色の帯と細かな信号が混ざる、高密度グリッチ。",
    backgroundColor: "#000000",
    layers: [
      { kind: "signal-noise", params: { scale: 95, amount: 0.85, detail: 4 } },
      {
        kind: "signal-noise",
        blend: "screen",
        opacity: 0.5,
        params: { scale: 24, amount: 0.55, detail: 8 },
      },
    ],
  },
  {
    id: "glitch-flare",
    name: "グリッチフレア",
    description: "強い光が横に流れる、スペクトルの残像。",
    backgroundColor: "#000000",
    layers: [
      { kind: "glitch-flare" },
      {
        kind: "signal-noise",
        opacity: 0.2,
        blend: "screen",
        params: { amount: 0.3, scale: 35 },
      },
    ],
  },
  {
    id: "color-film",
    name: "カラーフィルム",
    description: "赤と青のムラに、ほこりと細かな粒を重ねた質感。",
    backgroundColor: "#120a09",
    layers: [
      { kind: "color-film" },
      {
        kind: "film-damage",
        opacity: 0.6,
        params: { amount: 0.25, scale: 45, detail: 2 },
      },
    ],
  },
);

presets.push(
  {
    id: "latent-collapse",
    name: "生成エラー",
    description: "黒い穴と溶けた虹色。生成に失敗したような抽象素材。",
    backgroundColor: "#000000",
    layers: [
      { kind: "latent-bloom" },
      { kind: "rgb-shift", params: { scale: 1, amount: 0.3, detail: 1 } },
    ],
  },
  {
    id: "decoder-static",
    name: "壊れたデコード",
    description: "RGBの細かな砂嵐に色帯が流れる、復元途中のような画面。",
    backgroundColor: "#000000",
    layers: [
      { kind: "decode-noise" },
      {
        kind: "scanlines",
        opacity: 0.1,
        params: { scale: 3, amount: 0.3, detail: 1 },
      },
    ],
  },
);
